// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ExercisesCreateData, ExercisesCreateResponses, ExercisesEvaluateCreateData, ExercisesEvaluateCreateResponses, ExercisesFirstRetrieveData, ExercisesFirstRetrieveResponses, ExercisesNextRetrieveData, ExercisesNextRetrieveResponses, ExercisesRetrieveData, ExercisesRetrieveResponses, SchemaRetrieveData, SchemaRetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new range exercise
 */
export const exercisesCreate = <ThrowOnError extends boolean = false>(options: Options<ExercisesCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ExercisesCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/exercises/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get a range exercise by ID
 */
export const exercisesRetrieve = <ThrowOnError extends boolean = false>(options: Options<ExercisesRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ExercisesRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/exercises/{id}/',
        ...options
    });
};

/**
 * Evaluate an exercise's solution
 */
export const exercisesEvaluateCreate = <ThrowOnError extends boolean = false>(options: Options<ExercisesEvaluateCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<ExercisesEvaluateCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/exercises/{id}/evaluate/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get the next exercise after the current one
 */
export const exercisesNextRetrieve = <ThrowOnError extends boolean = false>(options: Options<ExercisesNextRetrieveData, ThrowOnError>) => {
    return (options.client ?? client).get<ExercisesNextRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/exercises/{id}/next/',
        ...options
    });
};

/**
 * Get the first exercise
 */
export const exercisesFirstRetrieve = <ThrowOnError extends boolean = false>(options?: Options<ExercisesFirstRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<ExercisesFirstRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/exercises/first/',
        ...options
    });
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<SchemaRetrieveData, ThrowOnError>) => {
    return (options?.client ?? client).get<SchemaRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'sessionid',
                type: 'apiKey'
            },
            {
                scheme: 'basic',
                type: 'http'
            }
        ],
        url: '/api/schema/',
        ...options
    });
};
