// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * * `lt` - lt
 * * `gt` - gt
 * * `between` - between
 */
export type ConstraintTypeEnum = 'lt' | 'gt' | 'between';

export type EvaluateSolution = {
    solution: Array<RangeExerciseDataPoint>;
};

export type EvaluateSolutionResponse = {
    is_correct: boolean;
};

export type NextExercise = {
    id: string | null;
};

export type RangeExerciseCreate = {
    title: string;
    description: string;
    constraint_type: ConstraintTypeEnum;
    lower_bound?: number | null;
    upper_bound?: number | null;
    is_active?: boolean;
    points: Array<RangeExerciseDataPointCreate>;
};

export type RangeExerciseDataPoint = {
    id: string;
    x: number;
    y: number;
    size: number;
};

export type RangeExerciseDataPointCreate = {
    x: number;
    y: number;
    size: number;
};

export type RangeExerciseResponse = {
    id: string;
    order: number;
    title: string;
    description: string;
    constraint_type: string;
    constraint_type_display: string;
    lower_bound: number | null;
    upper_bound: number | null;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    data_points: Array<RangeExerciseDataPoint>;
};

export type ExercisesCreateData = {
    body: RangeExerciseCreate;
    path?: never;
    query?: never;
    url: '/api/exercises/';
};

export type ExercisesCreateResponses = {
    201: RangeExerciseResponse;
};

export type ExercisesCreateResponse = ExercisesCreateResponses[keyof ExercisesCreateResponses];

export type ExercisesRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/exercises/{id}/';
};

export type ExercisesRetrieveResponses = {
    200: RangeExerciseResponse;
};

export type ExercisesRetrieveResponse = ExercisesRetrieveResponses[keyof ExercisesRetrieveResponses];

export type ExercisesEvaluateCreateData = {
    body: EvaluateSolution;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/exercises/{id}/evaluate/';
};

export type ExercisesEvaluateCreateResponses = {
    200: EvaluateSolutionResponse;
};

export type ExercisesEvaluateCreateResponse = ExercisesEvaluateCreateResponses[keyof ExercisesEvaluateCreateResponses];

export type ExercisesNextRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/exercises/{id}/next/';
};

export type ExercisesNextRetrieveResponses = {
    200: NextExercise;
};

export type ExercisesNextRetrieveResponse = ExercisesNextRetrieveResponses[keyof ExercisesNextRetrieveResponses];

export type ExercisesFirstRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/exercises/first/';
};

export type ExercisesFirstRetrieveResponses = {
    200: RangeExerciseResponse;
};

export type ExercisesFirstRetrieveResponse = ExercisesFirstRetrieveResponses[keyof ExercisesFirstRetrieveResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];
