# Generated by Django 5.2.8 on 2025-11-09 16:13

import django.db.models.deletion
import lessons.models.range_exercise
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RangeExercise',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.lesson')),
                ('description', models.TextField()),
                ('target_y_min', models.FloatField(blank=True, null=True)),
                ('target_y_max', models.FloatField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[(lessons.models.range_exercise.TargetType['LT'], 'less than'), (lessons.models.range_exercise.TargetType['GT'], 'greater than'), (lessons.models.range_exercise.TargetType['BETWEEN'], 'between')], max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('lessons.lesson',),
        ),
        migrations.CreateModel(
            name='RangeExerciseDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='x coordinate')),
                ('y', models.FloatField(help_text='y coordinate')),
                ('size', models.FloatField(help_text='Size of the bubble')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='lessons.rangeexercise')),
            ],
        ),
    ]
