// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { exercisesCreate, exercisesEvaluateCreate, exercisesFirstRetrieve, exercisesNextRetrieve, exercisesRetrieve, type Options, schemaRetrieve } from '../sdk.gen';
import type { ExercisesCreateData, ExercisesCreateResponse, ExercisesEvaluateCreateData, ExercisesEvaluateCreateResponse, ExercisesFirstRetrieveData, ExercisesNextRetrieveData, ExercisesRetrieveData, SchemaRetrieveData } from '../types.gen';

/**
 * Create a new range exercise
 */
export const exercisesCreateMutation = (options?: Partial<Options<ExercisesCreateData>>): UseMutationOptions<ExercisesCreateResponse, DefaultError, Options<ExercisesCreateData>> => {
    const mutationOptions: UseMutationOptions<ExercisesCreateResponse, DefaultError, Options<ExercisesCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await exercisesCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const exercisesRetrieveQueryKey = (options: Options<ExercisesRetrieveData>) => createQueryKey('exercisesRetrieve', options);

/**
 * Get a range exercise by ID
 */
export const exercisesRetrieveOptions = (options: Options<ExercisesRetrieveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exercisesRetrieve({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exercisesRetrieveQueryKey(options)
    });
};

/**
 * Evaluate an exercise's solution
 */
export const exercisesEvaluateCreateMutation = (options?: Partial<Options<ExercisesEvaluateCreateData>>): UseMutationOptions<ExercisesEvaluateCreateResponse, DefaultError, Options<ExercisesEvaluateCreateData>> => {
    const mutationOptions: UseMutationOptions<ExercisesEvaluateCreateResponse, DefaultError, Options<ExercisesEvaluateCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await exercisesEvaluateCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const exercisesNextRetrieveQueryKey = (options: Options<ExercisesNextRetrieveData>) => createQueryKey('exercisesNextRetrieve', options);

/**
 * Get the next exercise after the current one
 */
export const exercisesNextRetrieveOptions = (options: Options<ExercisesNextRetrieveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exercisesNextRetrieve({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exercisesNextRetrieveQueryKey(options)
    });
};

export const exercisesFirstRetrieveQueryKey = (options?: Options<ExercisesFirstRetrieveData>) => createQueryKey('exercisesFirstRetrieve', options);

/**
 * Get the first exercise
 */
export const exercisesFirstRetrieveOptions = (options?: Options<ExercisesFirstRetrieveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await exercisesFirstRetrieve({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: exercisesFirstRetrieveQueryKey(options)
    });
};

export const schemaRetrieveQueryKey = (options?: Options<SchemaRetrieveData>) => createQueryKey('schemaRetrieve', options);

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieveOptions = (options?: Options<SchemaRetrieveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await schemaRetrieve({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: schemaRetrieveQueryKey(options)
    });
};
